# Generated by Django 3.0.5 on 2021-07-11 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessToConsumer', '0003_auto_20210711_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerdetails',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
