# Generated by Django 3.0.5 on 2021-07-09 18:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20200921_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 9, 18, 56, 3, 707522, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='catalog.Item'),
        ),
    ]
