# Generated by Django 3.0.5 on 2021-07-09 19:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20210710_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 9, 19, 20, 59, 214179, tzinfo=utc)),
        ),
    ]
