# Generated by Django 3.0.5 on 2021-07-10 04:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20210710_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('F', 'Fruits'), ('V', 'Vegetables'), ('O', 'Others')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('F', 'Fast selling'), ('M', 'Medium paced'), ('S', 'Slow paced')], max_length=2),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 10, 4, 37, 47, 556123, tzinfo=utc)),
        ),
    ]
